"""home2

Revision ID: b69155fd1f74
Revises: 5ef032c2c27b
Create Date: 2026-05-11 19:24:28.873733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69155fd1f74'
down_revision: Union[str, Sequence[str], None] = '5ef032c2c27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funnel_stages', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('funnel_stages', sa.Column('kind', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funnel_stages', 'kind')
    op.drop_column('funnel_stages', 'is_archived')
    # ### end Alembic commands ###
